### ISSUE TITLE
Request for README.md

### ISSUE THREAD

**Issue by HelloElwin** [Carbonadooo/Search#1]
Hi, thanks for the great work! Could you please provide a README.md for better understanding of the project? Thank you!

**Comment by Carbonadooo** [comment]
Sorry this project is to be delete soon and there is no need for a readme.md file. Thank you for your concerning!



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 09:10 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Carbonadooo/Search] Request for README.md (Issue #1)




 
Hi, thanks for the great work! Could you please provide a README.md for better understanding of the project? Thank you!

**Comment by HelloElwin** [comment]
I see. Thanks for the late reply.
